# Generated by Django 3.2.7 on 2021-10-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='manager',
        ),
        migrations.AddField(
            model_name='event',
            name='manager',
            field=models.ManyToManyField(blank=True, null=True, related_name='_events_event_manager_+', to='events.MyClubUser'),
        ),
    ]
