# Generated by Django 3.2.8 on 2021-12-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_venue_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclubuser',
            name='password1',
            field=models.CharField(default='eduardo_1234', max_length=200),
        ),
        migrations.AddField(
            model_name='myclubuser',
            name='password2',
            field=models.CharField(default='eduardo_1234', max_length=200),
        ),
        migrations.AddField(
            model_name='myclubuser',
            name='username',
            field=models.CharField(default='default', max_length=30),
        ),
    ]
