# Generated by Django 3.2.8 on 2023-03-10 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20211213_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, default='No venue for this event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.venue'),
        ),
    ]
