# Generated by Django 3.2.8 on 2023-03-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_venue_venus_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='venus_image',
            new_name='venue_image',
        ),
    ]
